spring:
  application:
    name: product-service

  profiles:
    active: dev

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:3310/eureka